<?php

namespace App\Controller;

class GuestShowReviewsController extends UserShowReviewsController
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/show");
    }

    public function actionShowReview(): void
    {
        parent::actionShowReview(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/review");
    }

    public function actionShowOrganisationReviews(): void
    {
        parent::actionShowOrganisationReviews(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/reviews");
    }
}