<?php

namespace App\Controller;

class GuestOrganisationsController extends UserOrganisationsController
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestOrganisations/show");
    }

    public function actionShowOrganisationReviews(): void
    {
        parent::actionShowOrganisationReviews(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestOrganisations/organisation_reviews");
    }
}