<?php

namespace App\Controller;
/**
 *  Отвечает за отображение всех отзывы и информацию об организациях не зарегистрированным пользователям
 */
class GuestShowReviewsController extends UserShowReviewsController
{
    /**
     * Отображает список всех отзывов
     * @throws \Exception
     */
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/show");
    }

    /**
     * Отображает полную информацию о конкретном отзыве
     */
    public function actionShowReview(): void
    {
        parent::actionShowReview(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/review");
    }

    /**
     * Отображает информацию о конкретной организации и отзывы о ней
     */
    public function actionShowOrganisationReviews(): void
    {
        parent::actionShowOrganisationReviews(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("GuestShowReviews/reviews");
    }
}