<?php


namespace App\Controller;


use App\Model\OrganisationsModel;

class OrganisationsController extends Table
{
    protected string $tableName = 'organisations';

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new OrganisationsModel($config);
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/show');
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/add_edit');
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/add_edit');
    }

    public function actionAdd(): void
    {
//        parent::actionAdd(); // TODO: Change the autogenerated stub
        $workingHours = ['working_hours' => "$_POST[week_days]$_POST[start_hours]:$_POST[start_minutes]-$_POST[end_hours]:$_POST[end_minutes]"];
//        echo $workingHours['working_hours'];
        if (isset($_SESSION["user"]["id"])) {
            $this->model->addOrganisation($_POST['name'], $_POST['address'], $_POST['phone'], $_POST['social_networks'], $workingHours['working_hours'], $_POST['unp'], $_POST['legal_name'], $_POST['description']);
            $this->redirect("?type=Organisations&action=show");
        } else {
            $this->redirect("/");
        }
//        print_r($_POST);
    }
}