<?php


namespace App\Controller;


class OrganisationsController extends Table
{
    protected string $tableName = 'organisations';

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/show');
    }

    public function actionAdd(): void
    {
        parent::actionAdd(); // TODO: Change the autogenerated stub
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/add_edit');
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate('Organisations/add_edit');
    }

}