<?php

namespace App\Controller;
/**
 * Отвечает за отображение формы для добавления новой организации пользователем, а также осуществляет добавление
 */
class UserShowAddOrganisationController extends OrganisationsController
{

    /**
     *При попытке пользователя обратиться к методу для удаления данных, перенаправляет на главную страницу
     */
    public function actionDel(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для изменения данных, перенаправляет на главную страницу
     */
    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения всех данных, перенаправляет на главную страницу
     */
    public function actionShow(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения формы изменения данных, перенаправляет на главную страницу
     */
    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    /**
     *Осуществляет запись данных о новой организации в БД
     */
    public function actionAdd(): void
    {
        $workingHours = ['working_hours' => "$_POST[week_days]$_POST[start_hours]:$_POST[start_minutes]-$_POST[end_hours]:$_POST[end_minutes]"];
        if ($_POST && array_search("", $_POST) == false) {
            if (isset($_SESSION["user"]["id"])) {
                $this->model->addOrganisation($_POST['name'], $_POST['address'], $_POST['phone'], $_POST['social_networks'], $workingHours['working_hours'], $_POST['unp'], $_POST['legal_name'], $_POST['description']);
                $this->redirect("/");
            }
        } else {
            $this->redirect("?type=UserShowAddOrganisation&action=showadd");
        }
    }

    /**
     *Отображает форму для добавления новой организации
     */
    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("UserShowAddOrganisation/add");
    }
}