<?php

namespace App\Controller;

use App\Model\UserAddReviewModel;

/**
 * Отвечает за отображение формы для добавления отзыва пользователем, а также осуществляет добавление
 */
class UserShowAddReviewController extends ReviewsController
{
    /**
     * Осуществляет соединение с БД через "UserAddReviewModel"
     */
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UserAddReviewModel($config);
    }

    /**
     *При попытке пользователя обратиться к методу для удаления данных, перенаправляет на главную страницу
     */
    public function actionDel(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для изменения данных, перенаправляет на главную страницу
     */
    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения всех данных, перенаправляет на главную страницу
     */
    public function actionShow(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения формы изменения данных, перенаправляет на главную страницу
     */
    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    /**
     * Осуществляет запись нового отзыва в БД
     */
    public function actionAdd(): void
    {
        if ($_POST && !empty($_POST['title']) != '' && !empty($_POST['review']) != '' && !empty($_POST['organisations_id']) != '') {
            if (isset($_SESSION["user"]["id"])) {
                $this->model->addReview($_POST['title'], $_POST['review'], date('Y-m-d H:i:s'), $_POST['organisations_id'], $_SESSION['user']['id']);
                $this->redirect("?type=UserShowReviews&action=show");
            }
        } else {
            $this->redirect("?type=UserShowAddReview&action=showadd");
        }
    }

    /**
     * Отображает форму для добавления отзыва
     */
    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("UserShowAddReview/add");
    }
}