<?php

namespace App\Controller;

use App\Model\UserShowReviewsModel;

/**
 * Отвечает за отображение всех отзывы и информацию об организациях зарегистрированным пользователям
 */
class UserShowReviewsController extends ReviewsController
{
    /**
     * Осуществляет соединение с БД через "UserShowReviewsModel"
     */
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UserShowReviewsModel($config);
    }

    /**
     *При попытке пользователя обратиться к методу для удаления данных, перенаправляет на главную страницу
     */
    public function actionDel(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для изменения данных, перенаправляет на главную страницу
     */
    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения формы изменения данных, перенаправляет на главную страницу
     */
    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для отображения формы добавления данных, перенаправляет на главную страницу
     */
    public function actionShowAdd(): void
    {
        $this->redirect("/");
    }

    /**
     * При попытке пользователя обратиться к методу для добавления данных, перенаправляет на главную страницу
     */
    public function actionAdd(): void
    {
        $this->redirect("/");
    }


    /**
     * Отображает пользователю список всех отзывов
     * @throws \Exception
     */
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("UserShowReviews/show");
    }

    /**
     * Отображает пользователю отзыв и всю сопутствующую информацию
     * @throws \Exception
     */
    public function actionShowReview(): void
    {
        $this
            ->view
            ->addData([
                "review" => $this->model->getRow($_GET['id']),
                "comments" => $this->model->getReviewComments($_GET['id']),
                "columnComments" => $this->model->columnComments()
            ])
            ->setTemplate("UserShowReviews/review");
    }

    /**
     * Отображает пользователю информацию о конкретной организации и все отзывы о ней
     * @throws \Exception
     */
    public function actionShowOrganisationReviews(): void
    {
        $this
            ->view
            ->addData([
                "organisationInfo" => $this->model->getOrganisationInfo($_GET['id']),
                "review" => $this->model->getRow($_GET['id']),
                "organisationComments" => $this->model->getOrganisationReviews($_GET['id']),
                "columnComments" => $this->model->columnComments(),
                "organisationColumnComments" => $this->model->organisationColumnComments()
            ])
            ->setTemplate("UserShowReviews/reviews");
    }
}