<?php

namespace App\Controller;

class UserShowAddOrganisationController extends OrganisationsController
{

    public function actionDel(): void
    {
        $this->redirect("/");
    }

    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShow(): void
    {
        $this->redirect("/");
    }

    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    public function actionAdd(): void
    {
        $workingHours = ['working_hours' => "$_POST[week_days]$_POST[start_hours]:$_POST[start_minutes]-$_POST[end_hours]:$_POST[end_minutes]"];
        if ($_POST && array_search("", $_POST) == false) {
            if (isset($_SESSION["user"]["id"])) {
                $this->model->addOrganisation($_POST['name'], $_POST['address'], $_POST['phone'], $_POST['social_networks'], $workingHours['working_hours'], $_POST['unp'], $_POST['legal_name'], $_POST['description']);
                $this->redirect("/");
            }
        } else {
            $this->redirect("?type=UserShowAddOrganisation&action=showadd");
        }
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("UserShowAddOrganisation/add");
    }
}