<?php

namespace App\Controller;

use App\Model\UserShowReviewsModel;

class UserShowReviewsController extends ReviewsController
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UserShowReviewsModel($config);
    }

    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShowAdd(): void
    {
        $this->redirect("/");
    }

    public function actionDel(): void
    {
        $this->redirect("/");
    }

    public function actionAdd(): void
    {
        $this->redirect("/");
    }

    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "reviewsList" => $this->model->getReviews(),
            ])
            ->setTemplate("UserShowReviews/show");
    }

    public function actionShowReview()
    {
        $this
            ->view
            ->addData([
                "review" => $this->model->getRow($_GET['id']),
                "comments" => $this->model->getReviewComments($_GET['id']),
                "columnComments" => $this->model->columnComments()

            ])
            ->setTemplate("UserShowReviews/review");
    }

    public function actionShowOrganisationReviews()
    {
        $this
            ->view
            ->addData([
                "review" => $this->model->getRow($_GET['id']),
                "organisationComments" => $this->model->getOrganisationReviews($_GET['id']),
                "columnComments" => $this->model->columnComments()

            ])
            ->setTemplate("UserShowReviews/reviews");
    }
}