<?php

namespace App\Controller;

use App\Model\UserAddReviewModel;

class UserShowAddReviewController extends ReviewsController
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UserAddReviewModel($config);
    }

    public function actionDel(): void
    {
        $this->redirect("/");
    }

    public function actionEdit(): void
    {
        $this->redirect("/");
    }

    public function actionShow(): void
    {
        $this->redirect("/");
    }

    public function actionShowEdit(): void
    {
        $this->redirect("/");
    }

    public function actionAdd(): void
    {
        if ($_POST && !empty($_POST['title']) != '' && !empty($_POST['review']) != '' && !empty($_POST['organisations_id']) != '') {
            if (isset($_SESSION["user"]["id"])) {
                $this->model->addReview($_POST['title'], $_POST['review'], date('Y-m-d H:i:s'), $_POST['organisations_id'], $_SESSION['user']['id']);
                $this->redirect("?type=UserShowReviews&action=show");
            }
        } else {
            $this->redirect("?type=UserShowAddReview&action=showadd");
        }
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("UserShowAddReview/add");
    }
}